// RP2350A (Rpi pico 2 W)
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "uart_tx_8n2.pio.h"   // the .h auto generated by pioasm from .pio file
#include "uart_rx_8n1.pio.h"   // the .h auto generated by pioasm from .pio file
#include "rst.pio.h"   // the .h auto generated by pioasm from .pio file
#include "pulse_high.pio.h"   // the .h auto generated by pioasm from .pio file
#include "stdio.h"
#include "digests.h"
#include "pico/multicore.h"

#include "hardware/pio_instructions.h"
#include "pico/bootrom.h"
#include "boot/bootrom_constants.h"

#include <setjmp.h>

static jmp_buf dst;

inline void warp7() {
    longjmp(dst, 1);
}


#define DEBUG_MODE 0
const float UART_BAUD = 115200;

// core 1
const PIO RX_pio = pio0;
const uint RX_sm  = 1;          // use different pin & sm with TX, to use PIO_FIFO_JOIN_RX
const uint RX_PIN = 16;         // GP16 to avoid interferance with RST

// core 0
const PIO TX_pio = pio1; // pio0 or pio1
const uint TX_sm  = 0; // sm could be 0..3
const uint TX_PIN = 0;          // GP0

const PIO RST_pio = pio1;
const uint RST_sm  = 2;
const uint RST_PIN = 2;         // GP2

const uint POWER_CTL_PIN = 15;  // GP15

const uint GLITCH_CTL_PIN = 9;  // GP9
const PIO GLITCH_CTL_pio = pio0;
const uint GLITCH_CTL_sm = 0;

namespace RX {
    int offset;
    const PIO pio = RX_pio;
    const uint sm = RX_sm;
    const uint pin = RX_PIN;

    static inline void uart_rx_8n1_program_init(PIO pio, uint sm, uint offset, uint pin, uint baud) {
        pio_sm_set_pins_with_mask64(pio, sm, 1ull << pin, 1ull << pin); // initial high
        pio_sm_set_pindirs_with_mask64(pio, sm, 0ull << pin, 1ull << pin);
        pio_gpio_init(pio, pin);
    
        pio_sm_config c = uart_rx_8n1_program_get_default_config(offset);
        sm_config_set_in_pins(&c, pin); // for WAIT, IN
        sm_config_set_jmp_pin(&c, pin); // for JMP
        // shift_right=true, autopush=false
        sm_config_set_in_shift(&c, true, false, 8);
        // sm_config_set_in_shift(&c, true, true, 8);
        sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
        float div = (float)clock_get_hz(clk_sys) / (8*baud); // read 1 bit per 8 clock cycles
        sm_config_set_clkdiv(&c, div);
        
        pio_sm_init(pio, sm, offset, &c);
        // pio_sm_set_enabled(pio, sm, true);
    }
    
    static inline void on(){
        pio_sm_set_enabled(RX_pio, RX_sm, true);
    }
    
    static inline void off(){
        pio_sm_set_enabled(RX_pio, RX_sm, false);
    }
    
    /**
     * Return: -1               if FIFO empty
     * Return: uint8_t byte_val if data
     */
    // pin -> ISR -> RX FIFO
    // after sm1 start, it wait for a LOW and push 8 bits automatically to FIFO
    // No data: if a certain time pass, but FIFO is empty
    // give back control to TX if No data
    static inline int rx_getc(PIO pio, uint sm) {
        while (pio_sm_is_rx_fifo_empty(pio, sm))
            return -1;
        // should exists something, otherwise it's error
        uint32_t res = pio_sm_get_blocking(pio, sm);
        return (uint8_t) (res >> 24);
        // ok (document version)
        // 8-bit read from the uppermost byte of the FIFO, as data is left-justified
        // io_rw_8 *rxfifo_shift = (io_rw_8*)&pio->rxf[sm] + 3;
        // while (pio_sm_is_rx_fifo_empty(pio, sm))
        //     tight_loop_contents();
        // return (char)*rxfifo_shift;
    }
    
    /*
     * Return: the count of message consumed, in bytes
    */
    static inline int read_all() {
        int x = 0;
        int consumed_message_byte_count = 0;
        while ((x = rx_getc(RX_pio, RX_sm)) > 0)
        {
            printf("B:%x", x);
            consumed_message_byte_count++;
        }
        return consumed_message_byte_count;
    }
    /* Hold/pause RX, wait irq 5 to resume (set manually) */
    static void hold() {
        uint rx_jmp_hold = pio_encode_jmp(RX::offset + 9);
        pio_sm_exec_wait_blocking(RX_pio, RX_sm, rx_jmp_hold);
    }

    /* Set IRQ 5 */
    static void resume() {
        uint rx_irq_resume = pio_encode_irq_set(false, 5);
        pio_sm_exec_wait_blocking(RX_pio, RX_sm, rx_irq_resume);
    }
}


namespace TX {
    int offset;
    const PIO pio = TX_pio;
    const uint sm = TX_sm;
    const uint pin = TX_PIN;
    int ct = 0;
    /* ==== [WRITE] uart_tx_8n2_program START ==== */
    /**
     * IN pio: the PIO instance, pio0 or pio1
     * IN sm: the State machine index (0..3)
     * IN offset: the instruction offset of the loaded program
     * IN pin: abs pin number?
     * IN baud: baud
     */
    static void uart_tx_8n2_program_init(PIO pio, uint sm, uint offset, uint pin, float baud) {
        pio_sm_config c = uart_tx_8n2_program_get_default_config(offset);
        // Tell PIO to initially drive output-high on the selected pin, then map PIO
        // onto that pin with the IO muxes.
        pio_sm_set_pins_with_mask64(pio, sm, 1ull << pin, 1ull << pin);
        pio_sm_set_pindirs_with_mask64(pio, sm, 1ull << pin, 1ull << pin);
        // "pin" init -- GPIO control: PIO module takes control
        pio_gpio_init(pio, pin);
        // gpio_pull_up(pin);
        // set the direction of "pin" of pio in sm to output during the init
        // because we are the debugger and we write first
        pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true); // start from out
        sm_config_set_set_pins(&c, pin, 1);
        sm_config_set_out_pins(&c, pin, 1);
        // TX FIFO length=4 (4x32bits) is used for transmit, RX FIFO length=4 is used for receive.
        /* Each state machine has two FIFOs connecting to the system bus
         * Each FIFO is 4 * 32 bits
        */
        sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
        // sm_config_set_out_shift(&c, true, true, 8); // (c, shift_right=true, autopull=true, 8 bits a time) // FIFO (4x32bits) -> OSR (32 bits)
        sm_config_set_out_shift(&c, true, false, 8); // (c, shift_right=true, autopull=false, 8 bits a time) // FIFO (4x32bits) -> OSR (32 bits)
        sm_config_set_sideset_pins(&c, pin);
        float sys_hz = (float)clock_get_hz(clk_sys); // usually 125MHz
        /**
         * The clock divider slows the state machine’s execution by masking the system
         * clock on some cycles, in a repeating pattern, so that the state machine does
         * not advance. Effectively this produces a slower clock for the state machine
         * to run from, which can be used to generate e.g. a particular UART baud rate.
         * 
         * An integer clock divisor of n will cause the state machine to run 1 cycle in every n.
         * may jitter if div too small (when baud too high) and is float
        */
        sm_config_set_clkdiv(&c, sys_hz / (8 * baud)); // because we send 1 bit each 8 cycle
        // State_machine, load our configuration, and jump to the start of the program
        pio_sm_init(pio, sm, offset, &c);
        // State_machine, start
        // pio_sm_set_enabled(pio, sm, true);
    }
  
  
    /*
     * Each STATE_MACHINE has 2 FIFOs, each FIFO is 4x32 bits
     * the .pio `OUT pin 1` shift 1 bit from the *OSR* to the pin
     * (FIFO is not OSR, so either config autopull `sm_config_set_out_shift`, or `PULL` in .pio manually)
     * (if manually: use `sm_config_set_out_shift` but set autopull false (to achieve idle high etc.))
    */
    static void uart_tx_8n2_send_bytes(PIO pio, uint sm, const uint8_t *bytes, size_t length) {
        for (size_t i = 0; i < length; ++i) {
            // alternative raw method: // pio->txf[sm] = (125000000 / (2 * 250)) - 3;
            // the function stalls the processor when the TX FIFO is full
            // TX FIFO is 4 x 32 bits (uint32_t), but it's fine since the sm is configured to autopull 8 bits a time
            pio_sm_put_blocking(pio, sm, bytes[i]);
        }
    }
    static void send_test_bytes(PIO pio, uint sm){
        const uint8_t payload[] = { 0x1, 0x2, 0x3, 0x4, 0x55 };
        for (int i = 0; i < 1; i++){
            uart_tx_8n2_send_bytes(pio, sm, payload, sizeof(payload));
            sleep_ms(30); // "cpu" sleep means no data for FIFO in 30ms, which blocks the sm thus achieve idle HIGH
        }
    }
    static inline void on (){
        pio_sm_set_enabled(TX_pio, TX_sm, true);
    }
    static inline void off (){
        pio_sm_set_enabled(TX_pio, TX_sm, false);
    }
    /* halt exec, set line HIGH */
    static void holdHigh() {
        uint rst_irq_set = pio_encode_jmp(TX::offset + 7);
        // force irq on RST
        pio_sm_exec_wait_blocking(TX_pio, TX_sm, rst_irq_set);
    }

    /* halt exec, set line LOW */
    static void holdLow() {
        uint rst_irq_set = pio_encode_jmp(TX::offset + 10);
        // force irq on RST
        pio_sm_exec_wait_blocking(TX_pio, TX_sm, rst_irq_set);
    }

    static void resume() {
        uint tx_irq_set = pio_encode_irq_set(false, 6);
        pio_sm_exec_wait_blocking(TX_pio, TX_sm, tx_irq_set);
    }

    // static void uart_tx_8n2_send_byte(PIO pio, uint sm, const uint8_t *bytes, size_t length) {
    //     for (size_t i = 0; i < length; ++i) {
    //         // alternative raw method: // pio->txf[sm] = (125000000 / (2 * 250)) - 3;
    //         // the function stalls the processor when the TX FIFO is full
    //         // TX FIFO is 4 x 32 bits (uint32_t), but it's fine since the sm is configured to autopull 8 bits a time
    //         pio_sm_put_blocking(pio, sm, bytes[i]);
    //     }
    // }

    /**
     * the TX .pio send 1 byte, if FIFO has 1 byte only
     * so push 1 by one, receive, then next
     */
    static void send_digests(PIO pio, uint sm, const Digest *digests, const size_t num_digests, const double baud, const double starttime, const double endtime, const int delayMsFrame, const int delayMsSection) {
        const bool TARGET_DIR = true;    // only send when dir==true
        // bool       prevDir    = !TARGET_DIR; // force initial gap
        bool       prevDir    = TARGET_DIR;
        double     prevTime   = starttime;
        const double transmitTimePerBit = ((double) 1) / baud;
        for (size_t i = 0; i < NUM_DIGESTS; ++i) {
            const Digest &d = digests[i];
            // Skip unwanted directions, but remember last seen
            if (d.dir != TARGET_DIR) {
                prevDir = d.dir;
                prevTime = d.timestamp;
                continue;
            }
            double timeDiffBetweenBytes = d.timestamp - prevTime;
            // update prevTime
            prevTime = d.timestamp;
            // end if after end
            if (d.timestamp > endtime) {
                break;
            }
            // next if before start
            if (d.timestamp < starttime) {
                continue;
            }
            // Wait the response to finsh if new frame
            // Assume new frame when direction changed or reasonable delay is observed between packets
            // (since bidirectional) add logic later, for now just wait some time
            if (d.dir != prevDir || timeDiffBetweenBytes > transmitTimePerBit * 10 * 2) { // 2 bytes of 1+8N1
                sleep_ms(delayMsFrame);
                // RX::read_all();
            }
            // RX::read_all();
            // if ( timeDiffBetweenBytes > transmitTimePerBit * 3200) {
            //     sleep_ms(300);
            // }
            // otherwise, push 1 byte to FIFO
            pio_sm_put_blocking(pio, sm, d.byte_val);
            prevDir = d.dir;
            // RX::read_all();
            // sleep_ms(1);
            while (multicore_fifo_rvalid()) {
                multicore_fifo_pop_blocking();
                TX::ct++;
            }
        }
        // sleep_ms(500); // after a section
        sleep_ms(delayMsSection);
    }
}

namespace RST {
    int offset;
    const PIO pio = RST_pio;
    const uint sm = RST_sm;
    const uint pin = RST_PIN;

    // If initial RST logic handled in .pio, RST default LOW, wait IRQ, then flip HIGH/LOW
    // Otherwise (which is better), RST default HIGH, wait IRQ, then flip HIGH/LOW
    static void rst_init(PIO pio, uint sm, uint offset, uint pin, float baud) {
        pio_sm_config c = rst_program_get_default_config(offset);
        // RST is default HIGH
        pio_sm_set_pins_with_mask64(pio, sm, 1ull << pin, 1ull << pin);
        // pindir is default OUT
        pio_sm_set_pindirs_with_mask64(pio, sm, 1ull << pin, 1ull << pin);
        // "pin" init -- GPIO control: PIO module takes control
        pio_gpio_init(pio, pin);
        // gpio_pull_up(pin);
        pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true); // start from out
        sm_config_set_set_pins(&c, pin, 1); // RST use "SET" and "IRQ" only
        sm_config_set_jmp_pin(&c, pin); // jmp RST: to flip the pin
        sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX); // because RST is output only
        float sys_hz = (float)clock_get_hz(clk_sys); // usually 125MHz
        sm_config_set_clkdiv(&c, sys_hz / (8 * baud)); // because we send 1 bit each 8 cycle
        // State_machine, load our configuration, and jump to the start of the program
        pio_sm_init(pio, sm, offset, &c);
        // State_machine, start
        // pio_sm_set_enabled(pio, sm, true);
    }
    static void on() {
        pio_sm_set_enabled(pio, sm, true);
    }
    static void off() {
        pio_sm_set_enabled(pio, sm, false);
    }
    /* Force the IRQ 7 on the RST_sm, which will flip the RST line */
    static void flip() {
        uint rst_irq_set = pio_encode_irq_set(false, 7); // relative=false, IRQ 7
        // force irq on RST
        pio_sm_exec_wait_blocking(RST_pio, RST_sm, rst_irq_set);
    }
}


namespace GLITCH_CTL {
    const static int pin = GLITCH_CTL_PIN;
    const static PIO pio = GLITCH_CTL_pio;
    const static uint sm = GLITCH_CTL_sm;
    int offset;
    // account for the last byte's time
    // 9.5 (1+8N0.5) bytes * 1 / 115200 == 82.46527778 us
    // if pico 125MHz, divider 2, then 5154 cycles
    // response is 119.44 us after the starting LOW, delta 32.63
    // const int offset_base = 2565; // delay in clk
    // const int offset_max = 3531;  // 113 us
    // const int offset_base_inc = 100;     // + n per loop
    // const int offset_base = 10300; // delay in clk
    const int offset_base = 13000; // delay in clk
    const int offset_base_inc = 20;     // + n per loop
    // const int offset_max = 13500;  // 113 us
    const int offset_max = 13350;  // 113 us
    static int offset_ct_base = 0;
    static int offset_ct = offset_ct_base;

    // really depends on the component
    const int width_base = 1;  // time to hold during the glitch // 1 / 125M == 8 ns, 1 / 1M == 1us, 1 / 20M == 50 ns
    const int width_inc = 1;
    const int width_max = 1;
    static int width_inc_ct = 0;
    void glitch_ctl_pio_init(PIO pio, uint sm, uint offset, uint pin) {
        pio_sm_config c = uart_tx_8n2_program_get_default_config(offset);
        // Tell PIO to initially drive output-high on the selected pin, then map PIO
        // onto that pin with the IO muxes.
        pio_sm_set_pins_with_mask64(pio, sm, 0ull << pin, 1ull << pin);
        pio_sm_set_pindirs_with_mask64(pio, sm, 1ull << pin, 1ull << pin);
        // "pin" init -- GPIO control: PIO module takes control
        pio_gpio_init(pio, pin);
        // set the direction of "pin" of pio in sm to output during the init
        // because we are the debugger and we write first
        pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true); // start from out
        sm_config_set_set_pins(&c, pin, 1);
        sm_config_set_out_pins(&c, pin, 1);
        // TX FIFO length=4 (4x32bits) is used for transmit, RX FIFO length=4 is used for receive.
        /* Each state machine has two FIFOs connecting to the system bus
         * Each FIFO is 4 * 32 bits
        */
        sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
        sm_config_set_out_shift(&c, true, false, 16); // (c, shift_right=true, autopull=false, 8 bits a time) // FIFO (4x32bits) -> OSR (32 bits)
        sm_config_set_sideset_pins(&c, pin);
        float sys_hz = clock_get_hz(clk_sys); // usually 125MHz
        /**
         * The clock divider slows the state machine’s execution by masking the system
         * clock on some cycles, in a repeating pattern, so that the state machine does
         * not advance. Effectively this produces a slower clock for the state machine
         * to run from, which can be used to generate e.g. a particular UART baud rate.
         * 
         * An integer clock divisor of n will cause the state machine to run 1 cycle in every n.
         * may jitter if div too small (when baud too high) and is float
        */
        sm_config_set_clkdiv(&c, 1); // because we send 1 bit each 8 cycle
        // State_machine, load our configuration, and jump to the start of the program
        pio_sm_init(pio, sm, offset, &c);
        // State_machine, start
        // pio_sm_set_enabled(pio, sm, true);
    }

    static void on() {
        pio_sm_set_enabled(pio, sm, true);
    }
    static void off() {
        pio_sm_set_enabled(pio, sm, false);
    }
    void VERY_VERY_ANGRY() {
        int thisDelay = offset_base + offset_base_inc * offset_ct;
        int thisWidth = width_base + width_inc * width_inc_ct;
        if (thisDelay >= offset_max) {
            offset_ct = offset_ct_base;
            thisDelay = offset_base + offset_base_inc * offset_ct;

            width_inc_ct++;
            thisWidth = width_base + width_inc * width_inc_ct;
            if (thisWidth >= width_max) {
                width_inc_ct = 0;
                thisWidth = width_base;
            }
        }
        pio_sm_put_blocking(pio, sm, thisDelay); // delay
        // pio_sm_put_blocking(pio, sm, thisWidth); // pulse_width
        offset_ct++;

#if DEBUG_MODE == 1
        printf("ct:%d ", ct);
#endif
    }

}


namespace POWER_OUT {
    static int pin = POWER_CTL_PIN;
    static void po_gpio_init() {
        gpio_init(pin);
        gpio_set_dir(pin, GPIO_OUT);
    }
    static void on() {
        gpio_put(pin, 1); // HIGH
    }
    static void off() {
        gpio_put(pin, 0);
    }
    static void gpio_put_all_low() {
        gpio_init(TX::pin); // ? without the init, put not work in reset, hw bug ...? Anyway,
        gpio_init(RST::pin);
        // gpio_init(RX::pin);
        gpio_init(GLITCH_CTL::pin);
        gpio_set_dir(TX::pin, GPIO_OUT);
        gpio_set_dir(RST::pin, GPIO_OUT);
        // gpio_set_dir(RX::pin, GPIO_IN);
        gpio_set_dir(GLITCH_CTL::pin, GPIO_OUT);
        gpio_put(TX::pin, 0);
        gpio_put(RST::pin, 0);
        gpio_put(GLITCH_CTL::pin, 0);
    }
}



static void gpio_init_TXRST(){
    gpio_init(TX_PIN);
    gpio_init(RST_PIN);
    gpio_init(GLITCH_CTL::pin);
}
static void gpio_send_initial_state() {
    gpio_set_dir(TX_PIN, GPIO_OUT);
    gpio_set_dir(RST_PIN, GPIO_OUT);
    gpio_set_dir(GLITCH_CTL::pin, GPIO_OUT);
    gpio_put(TX_PIN, 1);  // TX HIGH
    gpio_put(RST_PIN, 0); // RST LOW
    gpio_put(GLITCH_CTL::pin, 0);
    sleep_ms(20);         // assume a initial state, nothing before this
}
// TX LOW 20ms, on 10ms RST HIGH
static void send_reset_via_gpio() {
    gpio_put(TX_PIN, 0);
    sleep_ms(10);
    gpio_put(RST_PIN, 1);
    sleep_ms(10);
    gpio_put(TX_PIN, 1); // TX HIGH
    sleep_ms(2);
}

static void gpio_send_eon() {
    TX::holdHigh();
    RST::flip();
    sleep_ms(5);
    TX::holdLow();
    sleep_ms(5);
    RST::flip();
    sleep_ms(5);
    TX::holdHigh();
    sleep_ms(5);
    TX::resume();
}
static void set_baud() {
      TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 16.6570, 16.6574, 1, 1);// 0x3a, single line
      TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 16.6574, 16.6584, 1, 5); // set baud, ACK
      TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 16.6870, 16.6886, 1, 3); // reset, ACK
      TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 16.689, 16.693, 1, 7); // Silicon Signature
      TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 16.693, 16.697, 1, 3); // Block Blank Check 0-0x0003ffff,Not Blank
}
void task_tx0() {
      set_baud();
      gpio_send_eon();

      TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 16.8359, 16.8383, 3, 10); // 0xc5, Set baud again, RST

      // ok1 TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 17.1, 17.1532431, 30, 30); // unlock (0xF2) ok
      // ok1 TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 29.21, 99, 30, 30); // ok
      TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 17.1, 17.153012690, 5, 10); // 2 bytes before unlock
}

void task_tx_remaining() {
      TX::send_digests(TX_pio, TX_sm, digests, NUM_DIGESTS, UART_BAUD, 29.21, 99, 30, 30);
}

/**
 * If RX on core1 (since TX logic is more complex)
 * - RX wait until IRQ 5
 * - RX read 3 bytes, send to core0, and print in serial monitor for debugging
 * - RX wait unitl IRQ 5 (Meanwhile, core0 check if data ok (chip unlocked))
 */
void task_rx() {
    RX::hold(); // do nothing initially, wait IRQ from main task
    // Wait for the first 3 bytes
    int byte_count = 0;
    int x;
    while (byte_count < 2)
    {
        x = -1;
        x = RX::rx_getc(RX_pio, RX_sm);
        if (x >= 0){
            /**
             * FIFOs across cores:
             * RP2040: 32bits * 8 * 2 FIFOs (TX, RX)
             * RP2350: 32bits * 4 * 2 FIFOs (TX, RX)
             * 
             * One of the FIFOs can only be written by core 0, and read by core 1.
             * The other can only be written by core 1, and read by core 0.
             */
            multicore_fifo_push_blocking(x);
#if DEBUG_MODE == 1
            printf("B:%x", x);
#endif
            byte_count++;
        }
    }
    RX::hold(); // pause and wait the main core, continue receiving if success
    while (true){
        x = -1;
        x = RX::rx_getc(RX_pio, RX_sm);
        if (x >= 0) {
            printf("B:%x", x);
            multicore_fifo_push_blocking(x);
        }
        // RX::read_all(); // monitor the FIFO
    }
}

/**
 * We need persistance memory to change the offset
 * - either use external memory
 * - or only reboot the 3v3 (chip)
 * - reset pico to initial state but keep memory
 * - reset core1
 */
static void partial_reset(int delay_ms) {
    TX::ct = 0;
    sleep_ms(int(delay_ms)/2);
    POWER_OUT::off(); // 3v3 powerer device must full reboot
    // there are better ways, but just reverse everything, it should work fine
    TX::off();
    RX::off();
    RST::off();
    GLITCH_CTL::off();
    pio_remove_program_and_unclaim_sm(&uart_tx_8n2_program, TX::pio, TX::sm, TX::offset);
    pio_remove_program_and_unclaim_sm(&uart_rx_8n1_program, RX::pio, RX::sm, RX::offset);
    pio_remove_program_and_unclaim_sm(&rst_program, RST::pio, RST::sm, RST::offset);
    pio_remove_program_and_unclaim_sm(&pulse_high_program, GLITCH_CTL::pio, GLITCH_CTL::sm, GLITCH_CTL::offset);
    POWER_OUT::gpio_put_all_low();
    // gpio_send_initial_state();
    multicore_reset_core1();
    sleep_ms(int(delay_ms/2));
    warp7(); // longjmp to main
}

static void run_multicore() {
    multicore_launch_core1(task_rx);
    task_tx0(); // until 1 bytes before
    RX::resume();
    while (!pio_sm_is_tx_fifo_empty(TX::pio, TX::sm)) { // Make sure all before has been sent
        tight_loop_contents();
    }
    uint8_t theLastByte = 0xff;
    pio_sm_put_blocking(TX_pio, TX_sm, theLastByte); // consider queuing a few bytes to add more wiggle room
    GLITCH_CTL::VERY_VERY_ANGRY();
    uint32_t y;
    // wait 100ms otherwise probably a crash
    if (!multicore_fifo_pop_timeout_us(100, &y)) { // Both the 1st byte were sent by TX, RX is core1 so we can receive it despite the pecking
        printf("crash1@%d,%d;", GLITCH_CTL::offset_ct, GLITCH_CTL::width_inc_ct); // actually ct+1
    }
    uint32_t x;
    if (!multicore_fifo_pop_timeout_us(100, &x)){ // Check the next bytes
        printf("crash2@%d,%d;", GLITCH_CTL::offset_ct, GLITCH_CTL::width_inc_ct); // actually ct+1
        partial_reset(40);
        return;
    }
    // x retrived
    if (((int)(x & 0xff) - 0xF2) != 0) { // 0xF2 unlock not ok
        partial_reset(40);
        return;
    } 
    // maybe success, send the cmds
    printf("\n OK@ct%d ", GLITCH_CTL::offset_ct); // actually ct+1
    TX::ct = 0;
    RX::resume();
    task_tx_remaining();
    printf("TX::ct==%d;", TX::ct); // actually ct+1
    printf("\n END");
    // if positive (~3472 bytes are sent by us)
    if (TX::ct < 4000) { // 3472
        printf("false_positive,TX::ct==%d;", TX::ct); // actually ct+1
        partial_reset(40);
        return;
    }

    while (true) {
        tight_loop_contents();
    }

    return;
}
static void hw_init() {
    POWER_OUT::po_gpio_init();

    gpio_init_TXRST();
    gpio_send_initial_state();
    POWER_OUT::on();
    send_reset_via_gpio(); // this has to be done before pio init because the initial reset logic is implented with gpio

    // Load program; return instruction memory offset the program is loaded at, or -1 for error
    TX::offset = pio_add_program(TX_pio, &uart_tx_8n2_program);
    if (TX::offset < 0) { printf("ERROR_CANNOT_LOAD_PROGRAM"); }
    TX::uart_tx_8n2_program_init(TX_pio, TX_sm, (uint)TX::offset, TX_PIN, UART_BAUD);

    RX::offset = pio_add_program(RX_pio, &uart_rx_8n1_program);
    hard_assert(RX::offset); // RX_offset >= 0;
    RX::uart_rx_8n1_program_init(RX_pio, RX_sm, (uint)RX::offset, RX_PIN, UART_BAUD);

    RST::offset = pio_add_program(RST_pio, &rst_program);
    hard_assert(RST::offset);
    RST::rst_init(RST_pio, RST_sm, (uint)RST::offset, RST_PIN, UART_BAUD);

    GLITCH_CTL::offset = pio_add_program(GLITCH_CTL::pio, &pulse_high_program);
    GLITCH_CTL::glitch_ctl_pio_init(GLITCH_CTL::pio, GLITCH_CTL::sm, (uint)GLITCH_CTL::offset, GLITCH_CTL::pin);
}
static void run() {
    TX::on();
    RX::on();
    RST::on();
    GLITCH_CTL::on();
    run_multicore();
}

int main() {
    if (setjmp(dst) == 0) {         // First call: 0, after a longjmp: 1
        stdio_init_all();           // USB COM printf init
    }

#if DEBUG_MODE == 1
    // sleep_ms(200);                  // a delay for USB COM to reconnect
#endif
    hw_init();
    run();
    while (true) tight_loop_contents();
    return 0;
}

